export class MapWorkflow {
	constructor() {}
	static getWorkFlowForMap(): any {
		return [
			{
				label: 'Assign',
				value: 'ASSIGN',
				status: 'PUBLISHED',
				roles: ['SPECIALIST'],
				message: 'Are you sure you want to assign this mapping?',
				notes: '',
				assign: true,
				edit: false,
			},
			{
				label: 'Assign',
				value: 'ASSIGN',
				status: 'NEW',
				roles: ['SPECIALIST'],
				message: 'Are you sure you want to assign this mapping?',
				notes: '',
				assign: true,
				edit: false,
			},
			{
				label: 'Assign',
				value: 'ASSIGN',
				status: 'READY_FOR_PUBLICATION',
				roles: ['SPECIALIST'],
				message: 'Are you sure you want to assign this mapping?',
				notes: '',
				assign: true,
				edit: false,
			},
			{
				label: 'Unassign',
				value: 'RELEASE',
				status: 'EDITING_IN_PROGRESS',
				roles: ['SPECIALIST'],
				message: 'Are you sure you want to unassign this mapping?',
				notes: '',
				assign: false,
				edit: true,
			},
			{
				label: 'Finish Editing',
				value: 'FINISH_EDITING',
				status: 'EDITING_IN_PROGRESS',
				roles: ['SPECIALIST'],
				message: 'Are you sure you want to finish editing this Mapping?',
				notes: '',
				assign: false,
				edit: true,
			},
			{
				label: 'Unassign',
				value: 'FORCE_RELEASE',
				status: 'EDITING_IN_PROGRESS',
				roles: ['ADMIN'],
				message: 'Are you sure you want to unassign this mapping?',
				notes: '',
				assign: false,
				edit: true,
			},
			{
				label: 'Reassign',
				value: 'REASSIGN',
				status: 'EDITING_IN_PROGRESS',
				roles: ['ADMIN', 'LEAD'],
				message: 'Are you sure you want to reassign this mapping?',
				notes: '',
				assign: true,
				edit: false,
			},
			{
				label: 'Request Review',
				value: 'REQUEST_REVIEW',
				status: 'EDITING_DONE',
				roles: ['SPECIALIST', 'LEAD'],
				message: 'Are you sure you want to request review this mapping?',
				notes: '',
				assign: false,
				edit: false,
			},
			{
				label: 'Approve',
				value: 'APPROVE_FOR_PUBLICATION',
				status: 'EDITING_DONE',
				roles: ['LEAD'],
				message: 'Are you sure you want to approve for publication this mapping?',
				notes: '',
				assign: false,
				edit: false,
			},
			{
				label: 'Start Review',
				value: 'START_REVIEW',
				status: 'REVIEW_NEEDED',
				roles: ['LEAD'],
				message: 'Are you sure you want to start reviewing this Mapping?',
				notes: '',
				assign: true,
				edit: false,
			},
			{
				label: 'Unassign',
				value: 'RELEASE',
				status: 'REVIEW_IN_PROGRESS',
				roles: ['LEAD'],
				message: 'Are you sure you want to unassign this mapping?',
				notes: '',
				assign: false,
				edit: true,
			},
			{
				label: 'Reassign',
				value: 'REASSIGN',
				status: 'REVIEW_IN_PROGRESS',
				roles: ['ADMIN', 'LEAD'],
				message: 'Are you sure you want to reassign this mapping?',
				notes: '',
				assign: true,
				edit: false,
			},
			{
				label: 'Unassign',
				value: 'FORCE_RELEASE',
				status: 'REVIEW_IN_PROGRESS',
				roles: ['ADMIN'],
				message: 'Are you sure you want to unassign this mapping?',
				notes: '',
				assign: false,
				edit: true,
			},
			{
				label: 'Accept Review',
				value: 'ACCEPT_REVIEW',
				status: 'REVIEW_IN_PROGRESS',
				roles: ['LEAD'],
				message: 'Are you sure you want to accept the review for this Mapping?',
				notes: '',
				assign: false,
				edit: true,
			},
		];
	}
}
